---
  test:
    adapter: sqlite3
    database: db/todo_test.sqlite3
  development:
    adapter: sqlite3
    database: db/todo_test.sqlite3
  production:
    adapter: sqlite3
    database: db/todo_test.sqlite3
